config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :vehicles
  resources :locations
  resources :driveroutes
  resources :bookmarks
  resources :routepoints
  resources :trips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
end

app/models/driveroute.rb
class Driveroute < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/routepoint.rb
class Routepoint < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/driveroutes_controller.rb
class DriveroutesController < ApplicationController
  def index
    @driveroutes = Driveroute.all
  end

  def new
    @title = "Add Route"
    @driveroute = Driveroute.new
  end

  def create
    driveroute = Driveroute.new(driveroute_params)
    if driveroute.save
        redirect_to driveroute
    else
      render :new
    end    
  end

  def show
    @driveroute = Driveroute.find(params[:id])
  end

  def edit
    @title = "Update Route"
    @driveroute = Driveroute.find(params[:id])
  end

  def update
    driveroute = Driveroute.find(params[:id])
    driveroute.update_attributes(driveroute_params)
    if driveroute.save
      redirect_to driveroute
    else
      render :edit
    end     
  end

  def destroy
    driveroute = Driveroute.find(params[:id])
    driveroute.destroy
    redirect_to root_url      
  end

  def driveroute_params
    params.require(:driveroute).permit(:route_name, :location_from, :location_to, :start_time, :end_time, :vehicle)
  end    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @title = "New Bookmark"
        @bookmark = Bookmark.new
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def new
    @title = "Add Location"
    @location = Location.new
  end

  def create
    location = Location.new(location_params)
    if location.save
        redirect_to location
    else
      render :new
    end   
  end

  def show
    @location = Location.find(params[:id])
  end

  def edit
    @title = "Update Location"
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    @location.update_attributes(location_params)
    if @location.save
      redirect_to @location
    else
      render :edit
    end    
  end

  def destroy
    location = Location.find(params[:id])
    location.destroy
    redirect_to root_url    
  end
  private

  def location_params
    params.require(:location).permit(:location_place, :city, :location_register, :location_address, :longitude, :latitude)
  end    
end

app/controllers/routepoints_controller.rb
class RoutepointsController < ApplicationController
  def index
    @routepoints = Routepoint.all
  end

  def show
    @routepoint = Routepoint.find(params[:id])
  end

  def new
    @title = "Add Routepoint"
    @routepoint = Routepoint.new
  end

  def create
    routepoints = Routepoint.new(routepoints_params)
    if routepoints.save
        redirect_to routepoints
    else
      render :new
    end
  end

  def edit
    @title = "Edit Routepoint"
    @routepoint = Routepoint.find(params[:id])
  end

  def update
    routepoint = Routepoint.find(params[:id])
    routepoint.update_attributes(routepoints_params)
    if routepoint.save
      redirect_to routepoint
    else
      render :edit
    end
  end

  def destroy
    routepoint = Routepoint.find(params[:id])
    routepoint.destroy
    redirect_to root_url     
  end
  
  private
    def routepoints_params
      params.require(:routepoint).permit(:route_id, :location_id)
    end   
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @title = "Add Trip"
    @trip = Trip.new
  end

  def create
    trip = Trip.new(trips_params)
    if trip.save
        redirect_to trip
    else
      render :new
    end    
  end

  def edit
    @title = "Edit Trip"
    @trip = Trip.find(params[:id])
  end

  def update
    trip = Trip.find(params[:id])
    trip.update_attributes(trips_params)
    if trip.save
      redirect_to trip
    else
      render :edit
    end    
  end

  def destroy
    trip = Trip.find(params[:id])
    trip.destroy
    redirect_to root_url     
  end
  private
    def trips_params
      params.require(:trip).permit(:vehicle_id, :route_id, :point_from, :point_to, :time_start, :time_to)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
    def index
      @vehicles = Vehicle.all
    end

    def new
        @title = "Add Vehicle"
        @vehicle = Vehicle.new
    end

    def create
        @vehicle = Vehicle.new(vehicle_params)
        if @vehicle.save
            redirect_to @vehicle
        else
          render :new
        end
    end 

    def show 
        @vehicle = Vehicle.find(params[:id])
    end

    def edit
        @title = "Update Vehicle"
        @vehicle = Vehicle.find(params[:id])
    end

    def update
        @vehicle = Vehicle.find(params[:id])
        @vehicle.update_attributes(vehicle_params)
        if @vehicle.save
          redirect_to @vehicle
        else
          render :edit
        end
    end  

    def destroy
        vehicle = Vehicle.find(params[:id])
        vehicle.destroy
        redirect_to root_url
    end     
    private
      def vehicle_params
        params.require(:vehicle).permit(:vehicle_name, :registration_number, :number_of_seats)
      end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/driveroutes_helper.rb
module DriveroutesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/routepoints_helper.rb
module RoutepointsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/bookmarks/edit.html.erb
<h1>Bookmarks#edit</h1>
<p>Find me in app/views/bookmarks/edit.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/driveroutes/_driveroute.html.erb
<div class="element_from_list">
    <div class="element_details">
        <div class="row">
            <div class="left">Route name</div>
            <div class="right"><%= @driveroute.route_name %></div>
        </div>
        <div class="row">
            <div class="left">Location From</div>
            <div class="right"><%= @driveroute.location_from %></div>
        </div> 
        <div class="row">
            <div class="left">Location To</div>
            <div class="right"><%= @driveroute.location_to %></div>
        </div>
        <div class="row">
            <div class="left">Start time</div>
            <div class="right"><%= @driveroute.start_time %></div>
        </div>    
        <div class="row">
            <div class="left">End time</div>
            <div class="right"><%= @driveroute.end_time %></div>
        </div>                          
    </div>
    <div class="options">
        <div><%= link_to 'Delete Route', driveroute_path(@driveroute), method: 'delete', class: 'btn btn-default del' %></div>
        <div><%= link_to 'Edit Route', edit_driveroute_path(@driveroute), class: 'btn btn-default upd' %></div>
    </div>
</div>

app/views/driveroutes/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @driveroute, html: {class: "form-horizontal"} do |f| %>
    <div class="center_box">
      <h2 class="center"><%= @title %></h2>
      <div class="padding_box">
        <div class="field">
          <%= f.label :route_name, class: "control-label col-sm-4" %>
          <%= f.text_field :route_name, class: "col-sm-8"  %>
        </div>

        <div class="field">
          <%= f.label :location_from, class: "control-label col-sm-4" %>
          <%= f.text_field :location_from, class: "col-sm-8"  %>
        </div>

        <div class="field">
          <%= f.label :location_to, class: "control-label col-sm-4" %>
          <%= f.text_field :location_to, class: "col-sm-8"  %>
        </div>

        <div class="field">
          <%= f.label :start_time, class: "control-label col-sm-4" %>
          <%= f.text_field :start_time, class: "col-sm-8"  %>
        </div>

        <div class="field">
          <%= f.label :end_time, class: "control-label col-sm-4" %>
          <%= f.text_field :end_time, class: "col-sm-8"  %>
        </div>

        <div class="field">
          <%= f.label :vehicle, class: "control-label col-sm-4" %>
          <%= f.text_field :vehicle, class: "col-sm-8"  %>
        </div>
        
        <div class="center">
          <%= f.submit "Add Route", class: 'btn btn-primary' %>
        </div>       
      </div>
   
    </div>

    <% end %>
  </div>
</div>

app/views/driveroutes/index.html.erb
<div class="list_of_the_elements">
    <h3>
        <span>Routes List</span>
        <%= link_to 'Add Route', new_driveroute_path, :class => 'navbar-link' %>
    </h3>
    <% if @driveroutes.count > 0 
        @driveroutes.each { | driveroute |
            @driveroute = driveroute %>
            <%= render 'driveroute' %>
    <% } end %>
</div>

app/views/driveroutes/show.html.erb
<div class="pull-right">
<%= link_to 'Delete Route', location_path(@driveroute), method: 'delete', class: 'btn btn-default' %>
<%= link_to 'Edit Route', edit_driveroute_path(@driveroute), class: 'btn btn-default' %>
</div>

app/views/locations/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @location, html: {class: "form-horizontal"} do |f| %>
      <div class="center_box">
        <h2 class="center"><%= @title %></h2>
        <div class="padding_box">
          <div class="field">
            <%= f.label :location_place, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :location_place, class: "col-sm-8"  %>
            </div>
          </div>

          <div class="field">
            <%= f.label :city, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :city, class: "col-sm-8"  %>
            </div>
          </div>

          <div class="field">
            <%= f.label :location_register, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :location_register, class: "col-sm-8"  %>
            </div>
          </div>

          <div class="field">
            <%= f.label :location_address, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :location_address, class: "col-sm-8"  %>
            </div>
          </div>

          <div class="field">
            <%= f.label :longitude, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :longitude, class: "col-sm-8"  %>
            </div>
          </div>

          <div class="field">
            <%= f.label :latitude, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :latitude, class: "col-sm-8"  %>
            </div>
          </div>
          <div id="latclicked"></div>
          <div id="longclicked"></div>
          
          <div id="latmoved"></div>
          <div id="longmoved"></div>      
          <div id="myMap" style="width:100%;height:400px;"></div>          
          <div class="center">
            <%= f.submit @title, class: 'btn btn-primary' %>
          </div>        
        </div>
     
      </div>

    <% end %>
  </div>
</div>
<script type="text/javascript">
</script>
<script type="text/javascript">
    function myMap() {
      var mapProp= {
        center:new google.maps.LatLng(51.508742,-0.120850),
        zoom:5,
      };
      var map = new google.maps.Map(document.getElementById("myMap"),mapProp);
      var myCenter = new google.maps.LatLng(document.getElementById("location_latitude").value, document.getElementById("location_longitude").value);
      var markers = [];

      google.maps.event.addListener(map, 'click', function(event) {
        placeMarker(map, event.latLng);
      });
      placeMarker(map, myCenter);
      function setMapOnAll(map) {
        for (var i = 0; i < markers.length; i++) {
          markers[i].setMap(map);
        }
      }      
      function placeMarker(map, location) {
        setMapOnAll(null);
        var marker = new google.maps.Marker({
          position: location,
          map: map
        });
        markers.push(marker);
        
        document.getElementById("location_longitude").value = location.lng();
        document.getElementById("location_latitude").value = location.lat();
        var infowindow = new google.maps.InfoWindow({
          
          content: 'Latitude: ' + location.lat() +
          '<br>Longitude: ' + location.lng()
        });
        infowindow.open(map,marker);
      }      
    }
  
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkXbqwNLi_EHzefCODmsjDLsJ_bR15Q9s&callback=myMap"></script>

app/views/locations/_location.html.erb
<div class="element_from_list">
    <div class="element_details">
        <div class="row">
            <div class="left">Location place</div>
            <div class="right"><%= @location.location_place %></div>
        </div>
        <div class="row">
            <div class="left">City</div>
            <div class="right"><%= @location.city %></div>
        </div> 
        <div class="row">
            <div class="left">Location Address</div>
            <div class="right"><%= @location.location_address %></div>
        </div>                         
    </div>
    <div class="options">
        <div><%= link_to 'Delete Location', location_path(@location), method: 'delete', class: 'btn btn-default del' %></div>
        <div><%= link_to 'Edit Location', edit_location_path(@location), class: 'btn btn-default upd' %></div>
    </div>
</div>

app/views/locations/edit.html.erb
<div class="form_page">
    <%= render 'form' %>
</div>

app/views/locations/index.html.erb
<div class="list_of_the_elements">
    <h3>
        <span>Locations List</span>
        <%= link_to 'Add Location', new_location_path, :class => 'navbar-link' %>
    </h3>
    <% if @locations.count > 0 
        @locations.each { | location |
            @location = location %>
            <%= render 'location' %>
    <% } end %>
</div>

app/views/locations/new.html.erb
<div class="form_page">
    <%= render 'form' %>
</div>

app/views/locations/show.html.erb
<div class="pull-right">
<%= link_to 'Delete Location', location_path(@location), method: 'delete', class: 'btn btn-default' %>
<%= link_to 'Edit Location', edit_location_path(@location), class: 'btn btn-default' %>
</div>

app/views/routepoints/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @routepoint, html: {class: "form-horizontal"} do |f| %>
      <div class="center_box">
        <h2 class="center"><%= @title %></h2>
        <div class="padding_box">
          <div class="field">
            <%= f.label :route_id, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.collection_select :route_id, Driveroute.order(:route_name),:id,:route_name, include_blank: true %>
            </div>
          </div>

          <div class="field">
            <%= f.label :location_id, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.collection_select :location_id, Location.order(:location_place),:id,:location_place, include_blank: true  %>
            </div>
          </div>          
          <div class="center">
            <%= f.submit @title, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/routepoints/_routepoint.html.erb
<div class="element_from_list">
    <div class="element_details">
        <div class="row">
            <div class="left">Route ID</div>
            <div class="right"><%= @routepoint.route_id %></div>
        </div>
        <div class="row">
            <div class="left">Location ID</div>
            <div class="right"><%= @routepoint.location_id %></div>
        </div> 
    </div>
    <div class="options">
        <div><%= link_to 'Delete Route Point', routepoint_path(@routepoint), method: 'delete', class: 'btn btn-default del' %></div>
        <div><%= link_to 'Edit Route Point', edit_routepoint_path(@routepoint), class: 'btn btn-default upd' %></div>
    </div>
</div>

app/views/routepoints/edit.html.erb
<div class="form_page">
    <%= render 'form' %>
</div>

app/views/routepoints/index.html.erb
<div class="list_of_the_elements">
    <h3>
        <span>Routepoints list</span>
        <%= link_to 'Add Routepoint', new_routepoint_path, :class => 'navbar-link' %>
    </h3>
    <% if @routepoints.count > 0 
        @routepoints.each { | routepoint |
            @routepoint = routepoint %>
            <%= render 'routepoint' %>
    <% } end %>
</div>

app/views/routepoints/new.html.erb
<div class="form_page">
    <%= render 'form' %>
</div>

app/views/routepoints/show.html.erb
<div class="pull-right">
<%= link_to 'Delete Route Point', routepoint_path(@routepoint), method: 'delete', class: 'btn btn-default' %>
<%= link_to 'Edit Vehicle', edit_routepoint_path(@routepoint), class: 'btn btn-default' %>
</div>

app/views/trips/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @trip, html: {class: "form-horizontal"} do |f| %>
      <div class="center_box">
        <h2 class="center"><%= @title %></h2>
        <div class="padding_box">
          <div class="field">
            <%= f.label :vehicle_id, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.collection_select :vehicle_id, Vehicle.order(:vehicle_name),:id,:vehicle_name, include_blank: true  %>
            </div>
          </div>

          <div class="field">
            <%= f.label :route_id, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.collection_select :route_id, Driveroute.order(:route_name),:id,:route_name, include_blank: true  %>
            </div>
          </div>
          <div class="field">
            <%= f.label :point_from, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.collection_select :point_from, Location.order(:location_place),:id,:location_place, include_blank: true  %>
            </div>
          </div>    
          
          <div class="field">
            <%= f.label :point_to, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.collection_select :point_to, Location.order(:location_place),:id,:location_place, include_blank: true  %>
            </div>
          </div>     
          <div class="field">
            <%= f.label :time_start, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :time_start, as: :date  %>
            </div>
          </div>
          <div class="field">
            <%= f.label :time_to, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :time_to, class: "col-sm-8"  %>
            </div>
          </div>                           
          <div class="center">
            <%= f.submit @title, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script>
$('.datetimepicker').datetimepicker();
</script>

app/views/trips/_trip.html.erb
<div class="element_from_list">
    <div class="element_details">
        <div class="row">
            <div class="left">Vehicle ID</div>
            <div class="right"><%= @trip.vehicle_id %></div>
        </div>
        <div class="row">
            <div class="left">Route ID</div>
            <div class="right"><%= @trip.route_id %></div>
        </div> 
        <div class="row">
            <div class="left">Start Location</div>
            <div class="right"><%= @trip.point_from %></div>
        </div>
        <div class="row">
            <div class="left">End Location</div>
            <div class="right"><%= @trip.point_to %></div>
        </div>   
        <div class="row">
            <div class="left">Time From</div>
            <div class="right"><%= @trip.time_start %></div>
        </div>
        <div class="row">
            <div class="left">Time To</div>
            <div class="right"><%= @trip.time_to %></div>
        </div>         
    </div>
    <div class="options">
        <div><%= link_to 'Delete Trip', trip_path(@trip), method: 'delete', class: 'btn btn-default del' %></div>
        <div><%= link_to 'Edit Trip', edit_trip_path(@trip), class: 'btn btn-default upd' %></div>
    </div>
</div>

app/views/trips/edit.html.erb
<div class="form_page">
    <%= render 'form' %>
</div>

app/views/trips/index.html.erb
<div class="list_of_the_elements">
    <h3>
        <span>Trips List</span>
        <%= link_to 'Add Trip', new_trip_path, :class => 'navbar-link' %>
    </h3>
    <% if @trips.count > 0 
        @trips.each { | trip |
            @trip = trip %>
            <%= render 'trip' %>
    <% } end %>
</div>

app/views/trips/new.html.erb
<div class="form_page">
    <%= render 'form' %>
</div>

app/views/trips/show.html.erb
<h1>Trips#show</h1>
<p>Find me in app/views/trips/show.html.erb</p>

app/views/vehicles/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @vehicle, html: {class: "form-horizontal"} do |f| %>
      <div class="center_box">
        <h2 class="center"><%= @title %></h2>
        <div class="padding_box">
          <div class="field">
            <%= f.label :vehicle_name, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :vehicle_name, class: "col-sm-8"  %>
            </div>
          </div>

          <div class="field">
            <%= f.label :registration_number, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :registration_number, class: "col-sm-8"  %>
            </div>
          </div>

          <div class="field">
            <%= f.label :number_of_seats, class: "control-label col-sm-4" %>
            <div class="input_field">
              <%= f.text_field :number_of_seats, class: "col-sm-8"  %>
            </div>
          </div>

          <div class="center">
            <%= f.submit @title, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/vehicles/_vehicle.html.erb
<div class="element_from_list">
    <div class="element_details">
        <div class="row">
            <div class="left">Vehicle name</div>
            <div class="right"><%= @vehicle.vehicle_name %></div>
        </div>
        <div class="row">
            <div class="left">Registration number</div>
            <div class="right"><%= @vehicle.registration_number %></div>
        </div> 
        <div class="row">
            <div class="left">Number of seats</div>
            <div class="right"><%= @vehicle.number_of_seats %></div>
        </div>               
    </div>
    <div class="options">
        <div><%= link_to 'Delete Vehicle', vehicle_path(@vehicle), method: 'delete', class: 'btn btn-default del' %></div>
        <div><%= link_to 'Edit Vehicle', edit_vehicle_path(@vehicle), class: 'btn btn-default upd' %></div>
    </div>
</div>

app/views/vehicles/edit.html.erb
<div class="form_page">
    <%= render 'form' %>
</div>

app/views/vehicles/index.html.erb
<div class="list_of_the_elements">
    <h3>
        <span>Vehicle list</span>
        <%= link_to 'Add Vehicle', new_vehicle_path, :class => 'navbar-link' %>
    </h3>
    <% if @vehicles.count > 0 
        @vehicles.each { | vehicle |
            @vehicle = vehicle %>
            <%= render 'vehicle' %>
    <% } end %>
</div>

app/views/vehicles/new.html.erb
<div class="form_page">
    <%= render 'form' %>
</div>

app/views/vehicles/show.html.erb
<div class="pull-right">
<%= link_to 'Delete Vehicle', vehicle_path(@vehicle), method: 'delete', class: 'btn btn-default' %>
<%= link_to 'Edit Vehicle', edit_vehicle_path(@vehicle), class: 'btn btn-default' %>
</div>