config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :vehicles
  resources :locations
  resources :driveroutes
  resources :bookmarks
  resources :routepoints
  resources :trips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
end

app/models/driveroute.rb
class Driveroute < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/routepoint.rb
class Routepoint < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @title = "New Bookmark"
        @bookmark = Bookmark.new
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def new
    @title = "Add Location"
    @location = Location.new
  end

  def create
    location = Location.new(location_params)
    if location.save
        redirect_to location
    else
      render :new
    end   
  end

  def show
    @location = Location.find(params[:id])
  end

  def edit
    @title = "Update Location"
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    @location.update_attributes(location_params)
    if @location.save
      redirect_to @location
    else
      render :edit
    end    
  end

  def destroy
    location = Location.find(params[:id])
    location.destroy
    redirect_to root_url    
  end
  private

  def location_params
    params.require(:location).permit(:location_place, :city, :location_register, :location_address, :longitude, :latitude)
  end    
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @title = "Add Trip"
    @trip = Trip.new
  end

  def create
    trip = Trip.new(trips_params)
    if trip.save
        redirect_to trip
    else
      render :new
    end    
  end

  def edit
    @title = "Edit Trip"
    @trip = Trip.find(params[:id])
  end

  def update
    trip = Trip.find(params[:id])
    trip.update_attributes(trips_params)
    if trip.save
      redirect_to trip
    else
      render :edit
    end    
  end

  def destroy
    trip = Trip.find(params[:id])
    trip.destroy
    redirect_to root_url     
  end
  private
    def trips_params
      params.require(:trip).permit(:vehicle_id, :route_id, :point_from, :point_to, :time_start, :time_to)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
    def index
      @vehicles = Vehicle.all
    end

    def new
        @title = "Add Vehicle"
        @vehicle = Vehicle.new
    end

    def create
        @vehicle = Vehicle.new(vehicle_params)
        if @vehicle.save
            redirect_to @vehicle
        else
          render :new
        end
    end 

    def show 
        @vehicle = Vehicle.find(params[:id])
    end

    def edit
        @title = "Update Vehicle"
        @vehicle = Vehicle.find(params[:id])
    end

    def update
        @vehicle = Vehicle.find(params[:id])
        @vehicle.update_attributes(vehicle_params)
        if @vehicle.save
          redirect_to @vehicle
        else
          render :edit
        end
    end  

    def destroy
        vehicle = Vehicle.find(params[:id])
        vehicle.destroy
        redirect_to root_url
    end     
    private
      def vehicle_params
        params.require(:vehicle).permit(:vehicle_name, :registration_number, :number_of_seats)
      end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/driveroutes_helper.rb
module DriveroutesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/routepoints_helper.rb
module RoutepointsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IrelandTransport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="layout">
      <div class="header">
        <% if user_signed_in? %>
          <span>Logged in as <strong><%= current_user.email %></strong>.</span>
        <% end %>
        <p class="navbar-text float-right">
        <%= link_to "Home", root_path %>
        <% if user_signed_in? %>
          <%= link_to 'Vehicles List', vehicles_path, :class => 'navbar-link' %>
          <%= link_to 'Routes List', driveroutes_path, :class => 'navbar-link' %>
          <%= link_to 'Trip List', trips_path, :class => 'navbar-link' %>
          <%= link_to 'Route Points', routepoints_path, :class => 'navbar-link' %>
          <%= link_to 'Locations List', locations_path, :class => 'navbar-link' %>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Destinations", new_user_registration_path, :class => 'navbar-link'  %>
          <%= link_to "Services", new_user_registration_path, :class => 'navbar-link'  %>
          <%= link_to "Pages", new_user_registration_path, :class => 'navbar-link'  %>
          <%= link_to "Users", new_user_registration_path, :class => 'navbar-link'  %>
          <%= link_to "Shop", new_user_registration_path, :class => 'navbar-link'  %>
          <%= link_to "Contact Us", new_user_registration_path, :class => 'navbar-link'  %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </p>      
      </div>
      <div class="container">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>    
    </div>      
    </div>


  </body>
</html>